Repository bitcoin-core/gui-qml, pull requests merged in 2021-11, with the labels that each got.

#76 doc: Add links to CI artifacts into README.md
  src/qml/README.md
Labels: Doc, UX

#67 Add OptionButton control
  src/Makefile.qt.include
  src/qml/bitcoin_qml.qrc
  src/qml/components/BlockCounter.qml
  src/qml/components/ConnectionOptions.qml
  src/qml/controls/OptionButton.qml
  src/qml/pages/stub.qml
Labels: UX

#77 build, doc: Ditch QtQuick.Controls 1
  build-aux/m4/bitcoin_qt.m4
  depends/packages/qt.mk
  depends/patches/qt/qt.pro
  src/qml/README.md
  src/qml/bitcoin.cpp
  src/qml/pages/initerrormessage.qml
Labels: Doc, Build system

#69 Add ProgressIndicator control
  src/Makefile.qt.include
  src/qml/bitcoin_qml.qrc
  src/qml/controls/ProgressIndicator.qml
  src/qml/pages/stub.qml
Labels: UX

#81 doc: introduce translator comment policy documentation
  src/qml/doc/translator-comments.md
Labels: Doc

#82 ci, doc: Add a link to Android APK CI artifact
  .cirrus.yml
  .github/PULL_REQUEST_TEMPLATE.md
  src/qml/README.md
Labels: Doc
