Repository bitcoin-core/gui-qml, pull requests merged in 2023-05, with the labels that each got.

#317 ci: build android 32 bit apk
  .cirrus.yml
  .github/PULL_REQUEST_TEMPLATE.md
  ci/test/00_setup_env_android32.sh
  configure.ac
  src/Makefile.qt.include
  src/qml/README.md
Labels: Android

#328 Remember network traffic graph scale
  src/qml/pages/node/NetworkTraffic.qml
Labels: Bug, enhancement

#330 Add proper versioning to About page
  src/qml/components/AboutOptions.qml
  src/qml/nodemodel.h
Labels: enhancement

#311 Introduce Display settings
  src/Makefile.qt.include
  src/qml/bitcoin_qml.qrc
  src/qml/components/BlockClock.qml
  src/qml/components/BlockClockDisplayMode.qml
  src/qml/components/PeersIndicator.qml
  src/qml/components/ThemeSettings.qml
  src/qml/components/blockclockdial.cpp
  src/qml/components/blockclockdial.h
  src/qml/controls/OptionButton.qml
  src/qml/controls/Theme.qml
  src/qml/imageprovider.cpp
  src/qml/pages/node/NodeRunner.qml
  src/qml/pages/node/NodeSettings.qml
  src/qml/pages/settings/SettingsBlockClockDisplayMode.qml
  src/qml/pages/settings/SettingsDisplay.qml
  src/qml/pages/settings/SettingsTheme.qml
  src/qml/res/icons/bitcoin-circle.png
  src/qml/res/icons/blockclock-size-compact.png
  src/qml/res/icons/blockclock-size-showcase.png
  src/qml/res/src/bitcoin-circle.svg
  src/qml/res/src/blockclock-size-compact.svg
  src/qml/res/src/blockclock-size-showcase.svg
Labels: UX, Needs design review, Design suggestion
