Repository bitcoin-core/gui-qml, pull requests merged in 2023-06, with the labels that each got.

#289 Don't use hover effects when on mobile
  src/qml/controls/ContinueButton.qml
  src/qml/controls/NavButton.qml
  src/qml/controls/OutlineButton.qml
  src/qml/controls/Setting.qml
  src/qml/controls/TextButton.qml
  src/qml/controls/ToggleButton.qml
Labels: Bug, UX, Needs design review

#331 Use node model state to update the android notification
  configure.ac
  src/Makefile.qt.include
  src/qml/androidnotifier.cpp
  src/qml/androidnotifier.h
  src/qml/bitcoin.cpp
  src/qt/android/src/org/bitcoincore/qt/BitcoinQtActivity.java
  src/qt/android/src/org/bitcoincore/qt/BitcoinQtService.java
Labels: Android

#344 Setup AppMode within InitErrorMessage
  src/qml/bitcoin.cpp
Labels: Bug
