Repository bitcoin-core/gui-qml, pull requests merged in 2023-07, with the labels that each got.

#325 Add looping animation to Estimating state
  src/qml/components/BlockClock.qml
Labels: UX, Needs design review

#352 Set implicitHeight on InformationPage
  src/qml/controls/InformationPage.qml
Labels: Bug, Android

#290 Make entire peers page scrollable
  src/qml/pages/node/NodeSettings.qml
  src/qml/pages/node/Peers.qml
Labels: UX
